// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhrzajraqiznandjkxwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpocnphanJhcWl6bmFuZGpreHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NzAxMTgsImV4cCI6MjA3MzE0NjExOH0.Go1RjaUZX7oHPktf0aaarJWDfYA7f-ID8bmEeSM5cUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});